; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=indvars -S | FileCheck %s
; PR4086

; Provide legal integer types.
target datalayout = "n8:16:32:64"

declare void @foo()

define void @test() {
; CHECK-LABEL: define void @test() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP_BODY:.*]]
; CHECK:       [[LOOP_BODY]]:
; CHECK-NEXT:    [[I_INT:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[NEXTI_INT:%.*]], %[[LOOP_BODY]] ]
; CHECK-NEXT:    tail call void @foo()
; CHECK-NEXT:    [[NEXTI_INT]] = add nuw nsw i32 [[I_INT]], 1
; CHECK-NEXT:    [[LESS:%.*]] = icmp samesign ult i32 [[NEXTI_INT]], 2
; CHECK-NEXT:    br i1 [[LESS]], label %[[LOOP_BODY]], label %[[DONE:.*]]
; CHECK:       [[DONE]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop_body

loop_body:
  %i = phi float [ %nexti, %loop_body ], [ 0.0, %entry ]
  tail call void @foo()
  %nexti = fadd float %i, 1.0
  %less = fcmp olt float %nexti, 2.0
  br i1 %less, label %loop_body, label %done

done:
  ret void
}
