; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=indvars -S | FileCheck %s

; Provide legal integer types.
target datalayout = "e-p:32:32:32-n8:16:32:64"


define void @foo(ptr nocapture %x, i32 %n) nounwind {
; CHECK-LABEL: define void @foo(
; CHECK-SAME: ptr captures(none) [[X:%.*]], i32 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP102:%.*]] = icmp sgt i32 [[N]], 0
; CHECK-NEXT:    br i1 [[TMP102]], label %[[BB_NPH:.*]], label %[[RETURN:.*]]
; CHECK:       [[BB_NPH]]:
; CHECK-NEXT:    [[TMP0:%.*]] = sext i32 [[N]] to i64
; CHECK-NEXT:    br label %[[BB:.*]]
; CHECK:       [[BB]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[BB7:.*]] ], [ 0, %[[BB_NPH]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = trunc nuw nsw i64 [[INDVARS_IV]] to i32
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i64, ptr [[X]], i32 [[TMP1]]
; CHECK-NEXT:    store i64 [[INDVARS_IV]], ptr [[TMP4]], align 8
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    br label %[[BB7]]
; CHECK:       [[BB7]]:
; CHECK-NEXT:    [[TMP10:%.*]] = icmp slt i64 [[INDVARS_IV_NEXT]], [[TMP0]]
; CHECK-NEXT:    br i1 [[TMP10]], label %[[BB]], label %[[BB7_RETURN_CRIT_EDGE:.*]]
; CHECK:       [[BB7_RETURN_CRIT_EDGE]]:
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    ret void
;
entry:
  %tmp102 = icmp sgt i32 %n, 0		; <i1> [#uses=1]
  br i1 %tmp102, label %bb.nph, label %return

bb.nph:		; preds = %entry
  br label %bb

bb:		; preds = %bb7, %bb.nph
  %i.01 = phi i32 [ %tmp6, %bb7 ], [ 0, %bb.nph ]		; <i32> [#uses=3]
  %tmp1 = sext i32 %i.01 to i64		; <i64> [#uses=1]
  %tmp4 = getelementptr i64, ptr %x, i32 %i.01		; <ptr> [#uses=1]
  store i64 %tmp1, ptr %tmp4, align 8
  %tmp6 = add i32 %i.01, 1		; <i32> [#uses=2]
  br label %bb7

bb7:		; preds = %bb
  %tmp10 = icmp slt i32 %tmp6, %n		; <i1> [#uses=1]
  br i1 %tmp10, label %bb, label %bb7.return_crit_edge

bb7.return_crit_edge:		; preds = %bb7
  br label %return

return:		; preds = %bb7.return_crit_edge, %entry
  ret void
}
